name: Build and test

on: push

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install oneAPI base toolkit
      run: wget https://registrationcenter-download.intel.com/akdlm/IRC_NAS/7deeaac4-f605-4bcf-a81b-ea7531577c61/l_BaseKit_p_2023.1.0.46401.sh && mkdir ONEAPI_ROOT && sudo sh ./l_BaseKit_p_2023.1.0.46401.sh -a --components intel.oneapi.lin.dpcpp-cpp-compiler -s --eula accept --install-dir ONEAPI_ROOT && export ONEAPI_ROOT=${PWD}/ONEAPI_ROOT

    - name: Set variables, configure and build
      run: |
        source ${PWD}/ONEAPI_ROOT/setvars.sh
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        source ${PWD}/ONEAPI_ROOT/setvars.sh
        ctest -C ${{env.BUILD_TYPE}} -V
